spring.application.name=StudentManagement
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/StudentManagement
spring.datasource.username=root
spring.datasource.password=saps@77290
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

